# -*- coding: utf-8 -*-
"""Text generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBo4h7Q6RlH90STKE_Xu7NSTb9N2Ea2-
"""

!pip install transformers torch

from transformers import pipeline
generator =pipeline("text-generation",model="gpt2")
prompt="Artificial Intelligences in finance will"
result=generator(
     prompt,
     max_new_tokens=50,
     num_return_sequences=1
     )
print("AI Generated Text:")
print(result[0]["generated_text"])